# Generated by Django 2.2.6 on 2019-10-22 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Guest',
            fields=[
                ('govt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=200)),
                ('Guest_members', models.IntegerField()),
                ('guest_phone_number', models.IntegerField()),
                ('guest_address', models.CharField(max_length=200)),
                ('bookingdate', models.DateField()),
                ('returndate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_type', models.CharField(max_length=200)),
                ('add_room', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('roomnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('guset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Hotel_Guest')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Room')),
            ],
        ),
        migrations.AddField(
            model_name='hotel_guest',
            name='roomType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Room'),
        ),
        migrations.CreateModel(
            name='Booking_records',
            fields=[
                ('Booking_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Booking_date', models.DateField()),
                ('room_rate', models.FloatField()),
                ('checkout_room', models.BooleanField()),
                ('cancel_booking', models.BooleanField()),
                ('return_date', models.DateField()),
                ('Booking_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Manager')),
                ('Guest_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Hotel_Guest')),
            ],
        ),
    ]
