# Generated by Django 2.2.6 on 2019-10-23 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_records',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
